version: '3.8'

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./srcs/nginx/
    networks:
      - inception
    ports:
      - 443:443
    env_file:
      - .env
    volumes:
      - wordpress:/var/www/html/wordpress
    restart: always
    init : true 
  mariadb:
    container_name: mariadb
    build: ./srcs/mariadb/
    restart: always
    environment:
      - MYSQL_ROOT_PASSWOR=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql/
    env_file:
      - .env
    networks:
      - inception
    init : true
  wordpress:
    container_name: wordpress
    build: ./srcs/wordpress
    volumes:
      - wordpress:/var/www/html/wordpress
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
      - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX}
    ports:
      - 9000:9000
    restart: always
    init : true

networks:
  inception:
    driver: bridge

volumes:
  wordpress:
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/wordpress/
  mariadb:
    driver_opts:
      type: none
      o: bind
      device: ${HOME}/data/mariadb/
