FROM debian:bullseye

WORKDIR /cadvisor/

RUN apt-get update && apt-get install -y wget

RUN wget https://github.com/google/cadvisor/releases/download/v0.37.0/cadvisor

RUN chmod +x cadvisor

CMD [ "./cadvisor" ]
